version: 2.1
orbs:
  node: cypress-io/cypress@1
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm ci
      - run:
          name: 'Cypress tests'
          command: npm run test:e2e:ci
          environment:
            AIRTABLE_API_KEY: $AIRTABLE_API_KEY
            AIRTABLE_BASE_ID: $AIRTABLE_BASE_ID
            GATSBY_ALGOLIA_APP_ID: $GATSBY_ALGOLIA_APP_ID
            GATSBY_ALGOLIA_SEARCH_KEY: $GATSBY_ALGOLIA_SEARCH_KEY
            GATSBY_ALGOLIA_INDEX: $GATSBY_ALGOLIA_INDEX
            GATSBY_GOOGLE_PLACES_API_KEY: $GATSBY_GOOGLE_PLACES_API_KEY
workflows:
  integration-tests:
    jobs:
      - test
