version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run:
                name: 'Cypress Tests'
                command: npm run test:e2e:ci
                environment:
                  AIRTABLE_API_KEY: $AIRTABLE_API_KEY
                  AIRTABLE_BASE_ID: $AIRTABLE_BASE_ID
                  GATSBY_ALGOLIA_APP_ID: $GATSBY_ALGOLIA_APP_ID
                  GATSBY_ALGOLIA_SEARCH_KEY: $GATSBY_ALGOLIA_SEARCH_KEY
                  GATSBY_ALGOLIA_INDEX: $GATSBY_ALGOLIA_INDEX
                  GATSBY_GOOGLE_PLACES_API_KEY: $GATSBY_GOOGLE_PLACES_API_KEY
workflows:
  build-deploy:
    jobs:
      - test:
          # run full test cycle for 'merge' or 'try'
          # filters:
          #   branches:
          #     only:
          #       - staging
          #       - trying
      # - publish:
      #     requires:
      #       - test
      #     # only publish site changes on 'merge'
      #     filters:
      #       branches:
      #         only: staging
